// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated from Python's unicodedata (Unicode 16.0.0) by taking the canonical
// decomposition (NFD) of every precomposed letter in Latin-1 Supplement, Latin
// Extended-A/B, Latin Extended Additional, Greek and Cyrillic, dropping its combining
// marks and lowering the case. DO NOT EDIT by hand; regenerate instead.

package untrusted

// baseLetters maps a precomposed letter to its base letter in lower case.
var baseLetters = map[rune]string{
	0x00C0: "a", // LATIN CAPITAL LETTER A WITH GRAVE
	0x00C1: "a", // LATIN CAPITAL LETTER A WITH ACUTE
	0x00C2: "a", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	0x00C3: "a", // LATIN CAPITAL LETTER A WITH TILDE
	0x00C4: "a", // LATIN CAPITAL LETTER A WITH DIAERESIS
	0x00C5: "a", // LATIN CAPITAL LETTER A WITH RING ABOVE
	0x00C7: "c", // LATIN CAPITAL LETTER C WITH CEDILLA
	0x00C8: "e", // LATIN CAPITAL LETTER E WITH GRAVE
	0x00C9: "e", // LATIN CAPITAL LETTER E WITH ACUTE
	0x00CA: "e", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	0x00CB: "e", // LATIN CAPITAL LETTER E WITH DIAERESIS
	0x00CC: "i", // LATIN CAPITAL LETTER I WITH GRAVE
	0x00CD: "i", // LATIN CAPITAL LETTER I WITH ACUTE
	0x00CE: "i", // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	0x00CF: "i", // LATIN CAPITAL LETTER I WITH DIAERESIS
	0x00D1: "n", // LATIN CAPITAL LETTER N WITH TILDE
	0x00D2: "o", // LATIN CAPITAL LETTER O WITH GRAVE
	0x00D3: "o", // LATIN CAPITAL LETTER O WITH ACUTE
	0x00D4: "o", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
	0x00D5: "o", // LATIN CAPITAL LETTER O WITH TILDE
	0x00D6: "o", // LATIN CAPITAL LETTER O WITH DIAERESIS
	0x00D9: "u", // LATIN CAPITAL LETTER U WITH GRAVE
	0x00DA: "u", // LATIN CAPITAL LETTER U WITH ACUTE
	0x00DB: "u", // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	0x00DC: "u", // LATIN CAPITAL LETTER U WITH DIAERESIS
	0x00DD: "y", // LATIN CAPITAL LETTER Y WITH ACUTE
	0x00E0: "a", // LATIN SMALL LETTER A WITH GRAVE
	0x00E1: "a", // LATIN SMALL LETTER A WITH ACUTE
	0x00E2: "a", // LATIN SMALL LETTER A WITH CIRCUMFLEX
	0x00E3: "a", // LATIN SMALL LETTER A WITH TILDE
	0x00E4: "a", // LATIN SMALL LETTER A WITH DIAERESIS
	0x00E5: "a", // LATIN SMALL LETTER A WITH RING ABOVE
	0x00E7: "c", // LATIN SMALL LETTER C WITH CEDILLA
	0x00E8: "e", // LATIN SMALL LETTER E WITH GRAVE
	0x00E9: "e", // LATIN SMALL LETTER E WITH ACUTE
	0x00EA: "e", // LATIN SMALL LETTER E WITH CIRCUMFLEX
	0x00EB: "e", // LATIN SMALL LETTER E WITH DIAERESIS
	0x00EC: "i", // LATIN SMALL LETTER I WITH GRAVE
	0x00ED: "i", // LATIN SMALL LETTER I WITH ACUTE
	0x00EE: "i", // LATIN SMALL LETTER I WITH CIRCUMFLEX
	0x00EF: "i", // LATIN SMALL LETTER I WITH DIAERESIS
	0x00F1: "n", // LATIN SMALL LETTER N WITH TILDE
	0x00F2: "o", // LATIN SMALL LETTER O WITH GRAVE
	0x00F3: "o", // LATIN SMALL LETTER O WITH ACUTE
	0x00F4: "o", // LATIN SMALL LETTER O WITH CIRCUMFLEX
	0x00F5: "o", // LATIN SMALL LETTER O WITH TILDE
	0x00F6: "o", // LATIN SMALL LETTER O WITH DIAERESIS
	0x00F9: "u", // LATIN SMALL LETTER U WITH GRAVE
	0x00FA: "u", // LATIN SMALL LETTER U WITH ACUTE
	0x00FB: "u", // LATIN SMALL LETTER U WITH CIRCUMFLEX
	0x00FC: "u", // LATIN SMALL LETTER U WITH DIAERESIS
	0x00FD: "y", // LATIN SMALL LETTER Y WITH ACUTE
	0x00FF: "y", // LATIN SMALL LETTER Y WITH DIAERESIS
	0x0100: "a", // LATIN CAPITAL LETTER A WITH MACRON
	0x0101: "a", // LATIN SMALL LETTER A WITH MACRON
	0x0102: "a", // LATIN CAPITAL LETTER A WITH BREVE
	0x0103: "a", // LATIN SMALL LETTER A WITH BREVE
	0x0104: "a", // LATIN CAPITAL LETTER A WITH OGONEK
	0x0105: "a", // LATIN SMALL LETTER A WITH OGONEK
	0x0106: "c", // LATIN CAPITAL LETTER C WITH ACUTE
	0x0107: "c", // LATIN SMALL LETTER C WITH ACUTE
	0x0108: "c", // LATIN CAPITAL LETTER C WITH CIRCUMFLEX
	0x0109: "c", // LATIN SMALL LETTER C WITH CIRCUMFLEX
	0x010A: "c", // LATIN CAPITAL LETTER C WITH DOT ABOVE
	0x010B: "c", // LATIN SMALL LETTER C WITH DOT ABOVE
	0x010C: "c", // LATIN CAPITAL LETTER C WITH CARON
	0x010D: "c", // LATIN SMALL LETTER C WITH CARON
	0x010E: "d", // LATIN CAPITAL LETTER D WITH CARON
	0x010F: "d", // LATIN SMALL LETTER D WITH CARON
	0x0112: "e", // LATIN CAPITAL LETTER E WITH MACRON
	0x0113: "e", // LATIN SMALL LETTER E WITH MACRON
	0x0114: "e", // LATIN CAPITAL LETTER E WITH BREVE
	0x0115: "e", // LATIN SMALL LETTER E WITH BREVE
	0x0116: "e", // LATIN CAPITAL LETTER E WITH DOT ABOVE
	0x0117: "e", // LATIN SMALL LETTER E WITH DOT ABOVE
	0x0118: "e", // LATIN CAPITAL LETTER E WITH OGONEK
	0x0119: "e", // LATIN SMALL LETTER E WITH OGONEK
	0x011A: "e", // LATIN CAPITAL LETTER E WITH CARON
	0x011B: "e", // LATIN SMALL LETTER E WITH CARON
	0x011C: "g", // LATIN CAPITAL LETTER G WITH CIRCUMFLEX
	0x011D: "g", // LATIN SMALL LETTER G WITH CIRCUMFLEX
	0x011E: "g", // LATIN CAPITAL LETTER G WITH BREVE
	0x011F: "g", // LATIN SMALL LETTER G WITH BREVE
	0x0120: "g", // LATIN CAPITAL LETTER G WITH DOT ABOVE
	0x0121: "g", // LATIN SMALL LETTER G WITH DOT ABOVE
	0x0122: "g", // LATIN CAPITAL LETTER G WITH CEDILLA
	0x0123: "g", // LATIN SMALL LETTER G WITH CEDILLA
	0x0124: "h", // LATIN CAPITAL LETTER H WITH CIRCUMFLEX
	0x0125: "h", // LATIN SMALL LETTER H WITH CIRCUMFLEX
	0x0128: "i", // LATIN CAPITAL LETTER I WITH TILDE
	0x0129: "i", // LATIN SMALL LETTER I WITH TILDE
	0x012A: "i", // LATIN CAPITAL LETTER I WITH MACRON
	0x012B: "i", // LATIN SMALL LETTER I WITH MACRON
	0x012C: "i", // LATIN CAPITAL LETTER I WITH BREVE
	0x012D: "i", // LATIN SMALL LETTER I WITH BREVE
	0x012E: "i", // LATIN CAPITAL LETTER I WITH OGONEK
	0x012F: "i", // LATIN SMALL LETTER I WITH OGONEK
	0x0130: "i", // LATIN CAPITAL LETTER I WITH DOT ABOVE
	0x0134: "j", // LATIN CAPITAL LETTER J WITH CIRCUMFLEX
	0x0135: "j", // LATIN SMALL LETTER J WITH CIRCUMFLEX
	0x0136: "k", // LATIN CAPITAL LETTER K WITH CEDILLA
	0x0137: "k", // LATIN SMALL LETTER K WITH CEDILLA
	0x0139: "l", // LATIN CAPITAL LETTER L WITH ACUTE
	0x013A: "l", // LATIN SMALL LETTER L WITH ACUTE
	0x013B: "l", // LATIN CAPITAL LETTER L WITH CEDILLA
	0x013C: "l", // LATIN SMALL LETTER L WITH CEDILLA
	0x013D: "l", // LATIN CAPITAL LETTER L WITH CARON
	0x013E: "l", // LATIN SMALL LETTER L WITH CARON
	0x0143: "n", // LATIN CAPITAL LETTER N WITH ACUTE
	0x0144: "n", // LATIN SMALL LETTER N WITH ACUTE
	0x0145: "n", // LATIN CAPITAL LETTER N WITH CEDILLA
	0x0146: "n", // LATIN SMALL LETTER N WITH CEDILLA
	0x0147: "n", // LATIN CAPITAL LETTER N WITH CARON
	0x0148: "n", // LATIN SMALL LETTER N WITH CARON
	0x014C: "o", // LATIN CAPITAL LETTER O WITH MACRON
	0x014D: "o", // LATIN SMALL LETTER O WITH MACRON
	0x014E: "o", // LATIN CAPITAL LETTER O WITH BREVE
	0x014F: "o", // LATIN SMALL LETTER O WITH BREVE
	0x0150: "o", // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
	0x0151: "o", // LATIN SMALL LETTER O WITH DOUBLE ACUTE
	0x0154: "r", // LATIN CAPITAL LETTER R WITH ACUTE
	0x0155: "r", // LATIN SMALL LETTER R WITH ACUTE
	0x0156: "r", // LATIN CAPITAL LETTER R WITH CEDILLA
	0x0157: "r", // LATIN SMALL LETTER R WITH CEDILLA
	0x0158: "r", // LATIN CAPITAL LETTER R WITH CARON
	0x0159: "r", // LATIN SMALL LETTER R WITH CARON
	0x015A: "s", // LATIN CAPITAL LETTER S WITH ACUTE
	0x015B: "s", // LATIN SMALL LETTER S WITH ACUTE
	0x015C: "s", // LATIN CAPITAL LETTER S WITH CIRCUMFLEX
	0x015D: "s", // LATIN SMALL LETTER S WITH CIRCUMFLEX
	0x015E: "s", // LATIN CAPITAL LETTER S WITH CEDILLA
	0x015F: "s", // LATIN SMALL LETTER S WITH CEDILLA
	0x0160: "s", // LATIN CAPITAL LETTER S WITH CARON
	0x0161: "s", // LATIN SMALL LETTER S WITH CARON
	0x0162: "t", // LATIN CAPITAL LETTER T WITH CEDILLA
	0x0163: "t", // LATIN SMALL LETTER T WITH CEDILLA
	0x0164: "t", // LATIN CAPITAL LETTER T WITH CARON
	0x0165: "t", // LATIN SMALL LETTER T WITH CARON
	0x0168: "u", // LATIN CAPITAL LETTER U WITH TILDE
	0x0169: "u", // LATIN SMALL LETTER U WITH TILDE
	0x016A: "u", // LATIN CAPITAL LETTER U WITH MACRON
	0x016B: "u", // LATIN SMALL LETTER U WITH MACRON
	0x016C: "u", // LATIN CAPITAL LETTER U WITH BREVE
	0x016D: "u", // LATIN SMALL LETTER U WITH BREVE
	0x016E: "u", // LATIN CAPITAL LETTER U WITH RING ABOVE
	0x016F: "u", // LATIN SMALL LETTER U WITH RING ABOVE
	0x0170: "u", // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
	0x0171: "u", // LATIN SMALL LETTER U WITH DOUBLE ACUTE
	0x0172: "u", // LATIN CAPITAL LETTER U WITH OGONEK
	0x0173: "u", // LATIN SMALL LETTER U WITH OGONEK
	0x0174: "w", // LATIN CAPITAL LETTER W WITH CIRCUMFLEX
	0x0175: "w", // LATIN SMALL LETTER W WITH CIRCUMFLEX
	0x0176: "y", // LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
	0x0177: "y", // LATIN SMALL LETTER Y WITH CIRCUMFLEX
	0x0178: "y", // LATIN CAPITAL LETTER Y WITH DIAERESIS
	0x0179: "z", // LATIN CAPITAL LETTER Z WITH ACUTE
	0x017A: "z", // LATIN SMALL LETTER Z WITH ACUTE
	0x017B: "z", // LATIN CAPITAL LETTER Z WITH DOT ABOVE
	0x017C: "z", // LATIN SMALL LETTER Z WITH DOT ABOVE
	0x017D: "z", // LATIN CAPITAL LETTER Z WITH CARON
	0x017E: "z", // LATIN SMALL LETTER Z WITH CARON
	0x01A0: "o", // LATIN CAPITAL LETTER O WITH HORN
	0x01A1: "o", // LATIN SMALL LETTER O WITH HORN
	0x01AF: "u", // LATIN CAPITAL LETTER U WITH HORN
	0x01B0: "u", // LATIN SMALL LETTER U WITH HORN
	0x01CD: "a", // LATIN CAPITAL LETTER A WITH CARON
	0x01CE: "a", // LATIN SMALL LETTER A WITH CARON
	0x01CF: "i", // LATIN CAPITAL LETTER I WITH CARON
	0x01D0: "i", // LATIN SMALL LETTER I WITH CARON
	0x01D1: "o", // LATIN CAPITAL LETTER O WITH CARON
	0x01D2: "o", // LATIN SMALL LETTER O WITH CARON
	0x01D3: "u", // LATIN CAPITAL LETTER U WITH CARON
	0x01D4: "u", // LATIN SMALL LETTER U WITH CARON
	0x01D5: "u", // LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
	0x01D6: "u", // LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
	0x01D7: "u", // LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
	0x01D8: "u", // LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
	0x01D9: "u", // LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
	0x01DA: "u", // LATIN SMALL LETTER U WITH DIAERESIS AND CARON
	0x01DB: "u", // LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
	0x01DC: "u", // LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
	0x01DE: "a", // LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
	0x01DF: "a", // LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
	0x01E0: "a", // LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
	0x01E1: "a", // LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
	0x01E2: "æ", // LATIN CAPITAL LETTER AE WITH MACRON
	0x01E3: "æ", // LATIN SMALL LETTER AE WITH MACRON
	0x01E6: "g", // LATIN CAPITAL LETTER G WITH CARON
	0x01E7: "g", // LATIN SMALL LETTER G WITH CARON
	0x01E8: "k", // LATIN CAPITAL LETTER K WITH CARON
	0x01E9: "k", // LATIN SMALL LETTER K WITH CARON
	0x01EA: "o", // LATIN CAPITAL LETTER O WITH OGONEK
	0x01EB: "o", // LATIN SMALL LETTER O WITH OGONEK
	0x01EC: "o", // LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
	0x01ED: "o", // LATIN SMALL LETTER O WITH OGONEK AND MACRON
	0x01EE: "ʒ", // LATIN CAPITAL LETTER EZH WITH CARON
	0x01EF: "ʒ", // LATIN SMALL LETTER EZH WITH CARON
	0x01F0: "j", // LATIN SMALL LETTER J WITH CARON
	0x01F4: "g", // LATIN CAPITAL LETTER G WITH ACUTE
	0x01F5: "g", // LATIN SMALL LETTER G WITH ACUTE
	0x01F8: "n", // LATIN CAPITAL LETTER N WITH GRAVE
	0x01F9: "n", // LATIN SMALL LETTER N WITH GRAVE
	0x01FA: "a", // LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
	0x01FB: "a", // LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
	0x01FC: "æ", // LATIN CAPITAL LETTER AE WITH ACUTE
	0x01FD: "æ", // LATIN SMALL LETTER AE WITH ACUTE
	0x01FE: "ø", // LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
	0x01FF: "ø", // LATIN SMALL LETTER O WITH STROKE AND ACUTE
	0x0200: "a", // LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
	0x0201: "a", // LATIN SMALL LETTER A WITH DOUBLE GRAVE
	0x0202: "a", // LATIN CAPITAL LETTER A WITH INVERTED BREVE
	0x0203: "a", // LATIN SMALL LETTER A WITH INVERTED BREVE
	0x0204: "e", // LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
	0x0205: "e", // LATIN SMALL LETTER E WITH DOUBLE GRAVE
	0x0206: "e", // LATIN CAPITAL LETTER E WITH INVERTED BREVE
	0x0207: "e", // LATIN SMALL LETTER E WITH INVERTED BREVE
	0x0208: "i", // LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
	0x0209: "i", // LATIN SMALL LETTER I WITH DOUBLE GRAVE
	0x020A: "i", // LATIN CAPITAL LETTER I WITH INVERTED BREVE
	0x020B: "i", // LATIN SMALL LETTER I WITH INVERTED BREVE
	0x020C: "o", // LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
	0x020D: "o", // LATIN SMALL LETTER O WITH DOUBLE GRAVE
	0x020E: "o", // LATIN CAPITAL LETTER O WITH INVERTED BREVE
	0x020F: "o", // LATIN SMALL LETTER O WITH INVERTED BREVE
	0x0210: "r", // LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
	0x0211: "r", // LATIN SMALL LETTER R WITH DOUBLE GRAVE
	0x0212: "r", // LATIN CAPITAL LETTER R WITH INVERTED BREVE
	0x0213: "r", // LATIN SMALL LETTER R WITH INVERTED BREVE
	0x0214: "u", // LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
	0x0215: "u", // LATIN SMALL LETTER U WITH DOUBLE GRAVE
	0x0216: "u", // LATIN CAPITAL LETTER U WITH INVERTED BREVE
	0x0217: "u", // LATIN SMALL LETTER U WITH INVERTED BREVE
	0x0218: "s", // LATIN CAPITAL LETTER S WITH COMMA BELOW
	0x0219: "s", // LATIN SMALL LETTER S WITH COMMA BELOW
	0x021A: "t", // LATIN CAPITAL LETTER T WITH COMMA BELOW
	0x021B: "t", // LATIN SMALL LETTER T WITH COMMA BELOW
	0x021E: "h", // LATIN CAPITAL LETTER H WITH CARON
	0x021F: "h", // LATIN SMALL LETTER H WITH CARON
	0x0226: "a", // LATIN CAPITAL LETTER A WITH DOT ABOVE
	0x0227: "a", // LATIN SMALL LETTER A WITH DOT ABOVE
	0x0228: "e", // LATIN CAPITAL LETTER E WITH CEDILLA
	0x0229: "e", // LATIN SMALL LETTER E WITH CEDILLA
	0x022A: "o", // LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
	0x022B: "o", // LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
	0x022C: "o", // LATIN CAPITAL LETTER O WITH TILDE AND MACRON
	0x022D: "o", // LATIN SMALL LETTER O WITH TILDE AND MACRON
	0x022E: "o", // LATIN CAPITAL LETTER O WITH DOT ABOVE
	0x022F: "o", // LATIN SMALL LETTER O WITH DOT ABOVE
	0x0230: "o", // LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
	0x0231: "o", // LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
	0x0232: "y", // LATIN CAPITAL LETTER Y WITH MACRON
	0x0233: "y", // LATIN SMALL LETTER Y WITH MACRON
	0x1E00: "a", // LATIN CAPITAL LETTER A WITH RING BELOW
	0x1E01: "a", // LATIN SMALL LETTER A WITH RING BELOW
	0x1E02: "b", // LATIN CAPITAL LETTER B WITH DOT ABOVE
	0x1E03: "b", // LATIN SMALL LETTER B WITH DOT ABOVE
	0x1E04: "b", // LATIN CAPITAL LETTER B WITH DOT BELOW
	0x1E05: "b", // LATIN SMALL LETTER B WITH DOT BELOW
	0x1E06: "b", // LATIN CAPITAL LETTER B WITH LINE BELOW
	0x1E07: "b", // LATIN SMALL LETTER B WITH LINE BELOW
	0x1E08: "c", // LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
	0x1E09: "c", // LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
	0x1E0A: "d", // LATIN CAPITAL LETTER D WITH DOT ABOVE
	0x1E0B: "d", // LATIN SMALL LETTER D WITH DOT ABOVE
	0x1E0C: "d", // LATIN CAPITAL LETTER D WITH DOT BELOW
	0x1E0D: "d", // LATIN SMALL LETTER D WITH DOT BELOW
	0x1E0E: "d", // LATIN CAPITAL LETTER D WITH LINE BELOW
	0x1E0F: "d", // LATIN SMALL LETTER D WITH LINE BELOW
	0x1E10: "d", // LATIN CAPITAL LETTER D WITH CEDILLA
	0x1E11: "d", // LATIN SMALL LETTER D WITH CEDILLA
	0x1E12: "d", // LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
	0x1E13: "d", // LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
	0x1E14: "e", // LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
	0x1E15: "e", // LATIN SMALL LETTER E WITH MACRON AND GRAVE
	0x1E16: "e", // LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
	0x1E17: "e", // LATIN SMALL LETTER E WITH MACRON AND ACUTE
	0x1E18: "e", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
	0x1E19: "e", // LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
	0x1E1A: "e", // LATIN CAPITAL LETTER E WITH TILDE BELOW
	0x1E1B: "e", // LATIN SMALL LETTER E WITH TILDE BELOW
	0x1E1C: "e", // LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
	0x1E1D: "e", // LATIN SMALL LETTER E WITH CEDILLA AND BREVE
	0x1E1E: "f", // LATIN CAPITAL LETTER F WITH DOT ABOVE
	0x1E1F: "f", // LATIN SMALL LETTER F WITH DOT ABOVE
	0x1E20: "g", // LATIN CAPITAL LETTER G WITH MACRON
	0x1E21: "g", // LATIN SMALL LETTER G WITH MACRON
	0x1E22: "h", // LATIN CAPITAL LETTER H WITH DOT ABOVE
	0x1E23: "h", // LATIN SMALL LETTER H WITH DOT ABOVE
	0x1E24: "h", // LATIN CAPITAL LETTER H WITH DOT BELOW
	0x1E25: "h", // LATIN SMALL LETTER H WITH DOT BELOW
	0x1E26: "h", // LATIN CAPITAL LETTER H WITH DIAERESIS
	0x1E27: "h", // LATIN SMALL LETTER H WITH DIAERESIS
	0x1E28: "h", // LATIN CAPITAL LETTER H WITH CEDILLA
	0x1E29: "h", // LATIN SMALL LETTER H WITH CEDILLA
	0x1E2A: "h", // LATIN CAPITAL LETTER H WITH BREVE BELOW
	0x1E2B: "h", // LATIN SMALL LETTER H WITH BREVE BELOW
	0x1E2C: "i", // LATIN CAPITAL LETTER I WITH TILDE BELOW
	0x1E2D: "i", // LATIN SMALL LETTER I WITH TILDE BELOW
	0x1E2E: "i", // LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
	0x1E2F: "i", // LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
	0x1E30: "k", // LATIN CAPITAL LETTER K WITH ACUTE
	0x1E31: "k", // LATIN SMALL LETTER K WITH ACUTE
	0x1E32: "k", // LATIN CAPITAL LETTER K WITH DOT BELOW
	0x1E33: "k", // LATIN SMALL LETTER K WITH DOT BELOW
	0x1E34: "k", // LATIN CAPITAL LETTER K WITH LINE BELOW
	0x1E35: "k", // LATIN SMALL LETTER K WITH LINE BELOW
	0x1E36: "l", // LATIN CAPITAL LETTER L WITH DOT BELOW
	0x1E37: "l", // LATIN SMALL LETTER L WITH DOT BELOW
	0x1E38: "l", // LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
	0x1E39: "l", // LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
	0x1E3A: "l", // LATIN CAPITAL LETTER L WITH LINE BELOW
	0x1E3B: "l", // LATIN SMALL LETTER L WITH LINE BELOW
	0x1E3C: "l", // LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
	0x1E3D: "l", // LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
	0x1E3E: "m", // LATIN CAPITAL LETTER M WITH ACUTE
	0x1E3F: "m", // LATIN SMALL LETTER M WITH ACUTE
	0x1E40: "m", // LATIN CAPITAL LETTER M WITH DOT ABOVE
	0x1E41: "m", // LATIN SMALL LETTER M WITH DOT ABOVE
	0x1E42: "m", // LATIN CAPITAL LETTER M WITH DOT BELOW
	0x1E43: "m", // LATIN SMALL LETTER M WITH DOT BELOW
	0x1E44: "n", // LATIN CAPITAL LETTER N WITH DOT ABOVE
	0x1E45: "n", // LATIN SMALL LETTER N WITH DOT ABOVE
	0x1E46: "n", // LATIN CAPITAL LETTER N WITH DOT BELOW
	0x1E47: "n", // LATIN SMALL LETTER N WITH DOT BELOW
	0x1E48: "n", // LATIN CAPITAL LETTER N WITH LINE BELOW
	0x1E49: "n", // LATIN SMALL LETTER N WITH LINE BELOW
	0x1E4A: "n", // LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
	0x1E4B: "n", // LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
	0x1E4C: "o", // LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
	0x1E4D: "o", // LATIN SMALL LETTER O WITH TILDE AND ACUTE
	0x1E4E: "o", // LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
	0x1E4F: "o", // LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
	0x1E50: "o", // LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
	0x1E51: "o", // LATIN SMALL LETTER O WITH MACRON AND GRAVE
	0x1E52: "o", // LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
	0x1E53: "o", // LATIN SMALL LETTER O WITH MACRON AND ACUTE
	0x1E54: "p", // LATIN CAPITAL LETTER P WITH ACUTE
	0x1E55: "p", // LATIN SMALL LETTER P WITH ACUTE
	0x1E56: "p", // LATIN CAPITAL LETTER P WITH DOT ABOVE
	0x1E57: "p", // LATIN SMALL LETTER P WITH DOT ABOVE
	0x1E58: "r", // LATIN CAPITAL LETTER R WITH DOT ABOVE
	0x1E59: "r", // LATIN SMALL LETTER R WITH DOT ABOVE
	0x1E5A: "r", // LATIN CAPITAL LETTER R WITH DOT BELOW
	0x1E5B: "r", // LATIN SMALL LETTER R WITH DOT BELOW
	0x1E5C: "r", // LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
	0x1E5D: "r", // LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
	0x1E5E: "r", // LATIN CAPITAL LETTER R WITH LINE BELOW
	0x1E5F: "r", // LATIN SMALL LETTER R WITH LINE BELOW
	0x1E60: "s", // LATIN CAPITAL LETTER S WITH DOT ABOVE
	0x1E61: "s", // LATIN SMALL LETTER S WITH DOT ABOVE
	0x1E62: "s", // LATIN CAPITAL LETTER S WITH DOT BELOW
	0x1E63: "s", // LATIN SMALL LETTER S WITH DOT BELOW
	0x1E64: "s", // LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
	0x1E65: "s", // LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
	0x1E66: "s", // LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
	0x1E67: "s", // LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
	0x1E68: "s", // LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
	0x1E69: "s", // LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
	0x1E6A: "t", // LATIN CAPITAL LETTER T WITH DOT ABOVE
	0x1E6B: "t", // LATIN SMALL LETTER T WITH DOT ABOVE
	0x1E6C: "t", // LATIN CAPITAL LETTER T WITH DOT BELOW
	0x1E6D: "t", // LATIN SMALL LETTER T WITH DOT BELOW
	0x1E6E: "t", // LATIN CAPITAL LETTER T WITH LINE BELOW
	0x1E6F: "t", // LATIN SMALL LETTER T WITH LINE BELOW
	0x1E70: "t", // LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
	0x1E71: "t", // LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
	0x1E72: "u", // LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
	0x1E73: "u", // LATIN SMALL LETTER U WITH DIAERESIS BELOW
	0x1E74: "u", // LATIN CAPITAL LETTER U WITH TILDE BELOW
	0x1E75: "u", // LATIN SMALL LETTER U WITH TILDE BELOW
	0x1E76: "u", // LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
	0x1E77: "u", // LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
	0x1E78: "u", // LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
	0x1E79: "u", // LATIN SMALL LETTER U WITH TILDE AND ACUTE
	0x1E7A: "u", // LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
	0x1E7B: "u", // LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
	0x1E7C: "v", // LATIN CAPITAL LETTER V WITH TILDE
	0x1E7D: "v", // LATIN SMALL LETTER V WITH TILDE
	0x1E7E: "v", // LATIN CAPITAL LETTER V WITH DOT BELOW
	0x1E7F: "v", // LATIN SMALL LETTER V WITH DOT BELOW
	0x1E80: "w", // LATIN CAPITAL LETTER W WITH GRAVE
	0x1E81: "w", // LATIN SMALL LETTER W WITH GRAVE
	0x1E82: "w", // LATIN CAPITAL LETTER W WITH ACUTE
	0x1E83: "w", // LATIN SMALL LETTER W WITH ACUTE
	0x1E84: "w", // LATIN CAPITAL LETTER W WITH DIAERESIS
	0x1E85: "w", // LATIN SMALL LETTER W WITH DIAERESIS
	0x1E86: "w", // LATIN CAPITAL LETTER W WITH DOT ABOVE
	0x1E87: "w", // LATIN SMALL LETTER W WITH DOT ABOVE
	0x1E88: "w", // LATIN CAPITAL LETTER W WITH DOT BELOW
	0x1E89: "w", // LATIN SMALL LETTER W WITH DOT BELOW
	0x1E8A: "x", // LATIN CAPITAL LETTER X WITH DOT ABOVE
	0x1E8B: "x", // LATIN SMALL LETTER X WITH DOT ABOVE
	0x1E8C: "x", // LATIN CAPITAL LETTER X WITH DIAERESIS
	0x1E8D: "x", // LATIN SMALL LETTER X WITH DIAERESIS
	0x1E8E: "y", // LATIN CAPITAL LETTER Y WITH DOT ABOVE
	0x1E8F: "y", // LATIN SMALL LETTER Y WITH DOT ABOVE
	0x1E90: "z", // LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
	0x1E91: "z", // LATIN SMALL LETTER Z WITH CIRCUMFLEX
	0x1E92: "z", // LATIN CAPITAL LETTER Z WITH DOT BELOW
	0x1E93: "z", // LATIN SMALL LETTER Z WITH DOT BELOW
	0x1E94: "z", // LATIN CAPITAL LETTER Z WITH LINE BELOW
	0x1E95: "z", // LATIN SMALL LETTER Z WITH LINE BELOW
	0x1E96: "h", // LATIN SMALL LETTER H WITH LINE BELOW
	0x1E97: "t", // LATIN SMALL LETTER T WITH DIAERESIS
	0x1E98: "w", // LATIN SMALL LETTER W WITH RING ABOVE
	0x1E99: "y", // LATIN SMALL LETTER Y WITH RING ABOVE
	0x1E9B: "ſ", // LATIN SMALL LETTER LONG S WITH DOT ABOVE
	0x1EA0: "a", // LATIN CAPITAL LETTER A WITH DOT BELOW
	0x1EA1: "a", // LATIN SMALL LETTER A WITH DOT BELOW
	0x1EA2: "a", // LATIN CAPITAL LETTER A WITH HOOK ABOVE
	0x1EA3: "a", // LATIN SMALL LETTER A WITH HOOK ABOVE
	0x1EA4: "a", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
	0x1EA5: "a", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
	0x1EA6: "a", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
	0x1EA7: "a", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
	0x1EA8: "a", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
	0x1EA9: "a", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
	0x1EAA: "a", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
	0x1EAB: "a", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
	0x1EAC: "a", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
	0x1EAD: "a", // LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
	0x1EAE: "a", // LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
	0x1EAF: "a", // LATIN SMALL LETTER A WITH BREVE AND ACUTE
	0x1EB0: "a", // LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
	0x1EB1: "a", // LATIN SMALL LETTER A WITH BREVE AND GRAVE
	0x1EB2: "a", // LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
	0x1EB3: "a", // LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
	0x1EB4: "a", // LATIN CAPITAL LETTER A WITH BREVE AND TILDE
	0x1EB5: "a", // LATIN SMALL LETTER A WITH BREVE AND TILDE
	0x1EB6: "a", // LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
	0x1EB7: "a", // LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
	0x1EB8: "e", // LATIN CAPITAL LETTER E WITH DOT BELOW
	0x1EB9: "e", // LATIN SMALL LETTER E WITH DOT BELOW
	0x1EBA: "e", // LATIN CAPITAL LETTER E WITH HOOK ABOVE
	0x1EBB: "e", // LATIN SMALL LETTER E WITH HOOK ABOVE
	0x1EBC: "e", // LATIN CAPITAL LETTER E WITH TILDE
	0x1EBD: "e", // LATIN SMALL LETTER E WITH TILDE
	0x1EBE: "e", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
	0x1EBF: "e", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
	0x1EC0: "e", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
	0x1EC1: "e", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
	0x1EC2: "e", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
	0x1EC3: "e", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
	0x1EC4: "e", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
	0x1EC5: "e", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
	0x1EC6: "e", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
	0x1EC7: "e", // LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
	0x1EC8: "i", // LATIN CAPITAL LETTER I WITH HOOK ABOVE
	0x1EC9: "i", // LATIN SMALL LETTER I WITH HOOK ABOVE
	0x1ECA: "i", // LATIN CAPITAL LETTER I WITH DOT BELOW
	0x1ECB: "i", // LATIN SMALL LETTER I WITH DOT BELOW
	0x1ECC: "o", // LATIN CAPITAL LETTER O WITH DOT BELOW
	0x1ECD: "o", // LATIN SMALL LETTER O WITH DOT BELOW
	0x1ECE: "o", // LATIN CAPITAL LETTER O WITH HOOK ABOVE
	0x1ECF: "o", // LATIN SMALL LETTER O WITH HOOK ABOVE
	0x1ED0: "o", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
	0x1ED1: "o", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
	0x1ED2: "o", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
	0x1ED3: "o", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
	0x1ED4: "o", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
	0x1ED5: "o", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
	0x1ED6: "o", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
	0x1ED7: "o", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
	0x1ED8: "o", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
	0x1ED9: "o", // LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
	0x1EDA: "o", // LATIN CAPITAL LETTER O WITH HORN AND ACUTE
	0x1EDB: "o", // LATIN SMALL LETTER O WITH HORN AND ACUTE
	0x1EDC: "o", // LATIN CAPITAL LETTER O WITH HORN AND GRAVE
	0x1EDD: "o", // LATIN SMALL LETTER O WITH HORN AND GRAVE
	0x1EDE: "o", // LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
	0x1EDF: "o", // LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
	0x1EE0: "o", // LATIN CAPITAL LETTER O WITH HORN AND TILDE
	0x1EE1: "o", // LATIN SMALL LETTER O WITH HORN AND TILDE
	0x1EE2: "o", // LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
	0x1EE3: "o", // LATIN SMALL LETTER O WITH HORN AND DOT BELOW
	0x1EE4: "u", // LATIN CAPITAL LETTER U WITH DOT BELOW
	0x1EE5: "u", // LATIN SMALL LETTER U WITH DOT BELOW
	0x1EE6: "u", // LATIN CAPITAL LETTER U WITH HOOK ABOVE
	0x1EE7: "u", // LATIN SMALL LETTER U WITH HOOK ABOVE
	0x1EE8: "u", // LATIN CAPITAL LETTER U WITH HORN AND ACUTE
	0x1EE9: "u", // LATIN SMALL LETTER U WITH HORN AND ACUTE
	0x1EEA: "u", // LATIN CAPITAL LETTER U WITH HORN AND GRAVE
	0x1EEB: "u", // LATIN SMALL LETTER U WITH HORN AND GRAVE
	0x1EEC: "u", // LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
	0x1EED: "u", // LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
	0x1EEE: "u", // LATIN CAPITAL LETTER U WITH HORN AND TILDE
	0x1EEF: "u", // LATIN SMALL LETTER U WITH HORN AND TILDE
	0x1EF0: "u", // LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
	0x1EF1: "u", // LATIN SMALL LETTER U WITH HORN AND DOT BELOW
	0x1EF2: "y", // LATIN CAPITAL LETTER Y WITH GRAVE
	0x1EF3: "y", // LATIN SMALL LETTER Y WITH GRAVE
	0x1EF4: "y", // LATIN CAPITAL LETTER Y WITH DOT BELOW
	0x1EF5: "y", // LATIN SMALL LETTER Y WITH DOT BELOW
	0x1EF6: "y", // LATIN CAPITAL LETTER Y WITH HOOK ABOVE
	0x1EF7: "y", // LATIN SMALL LETTER Y WITH HOOK ABOVE
	0x1EF8: "y", // LATIN CAPITAL LETTER Y WITH TILDE
	0x1EF9: "y", // LATIN SMALL LETTER Y WITH TILDE
	0x0385: "¨", // GREEK DIALYTIKA TONOS
	0x0386: "α", // GREEK CAPITAL LETTER ALPHA WITH TONOS
	0x0388: "ε", // GREEK CAPITAL LETTER EPSILON WITH TONOS
	0x0389: "η", // GREEK CAPITAL LETTER ETA WITH TONOS
	0x038A: "ι", // GREEK CAPITAL LETTER IOTA WITH TONOS
	0x038C: "ο", // GREEK CAPITAL LETTER OMICRON WITH TONOS
	0x038E: "υ", // GREEK CAPITAL LETTER UPSILON WITH TONOS
	0x038F: "ω", // GREEK CAPITAL LETTER OMEGA WITH TONOS
	0x0390: "ι", // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
	0x03AA: "ι", // GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
	0x03AB: "υ", // GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
	0x03AC: "α", // GREEK SMALL LETTER ALPHA WITH TONOS
	0x03AD: "ε", // GREEK SMALL LETTER EPSILON WITH TONOS
	0x03AE: "η", // GREEK SMALL LETTER ETA WITH TONOS
	0x03AF: "ι", // GREEK SMALL LETTER IOTA WITH TONOS
	0x03B0: "υ", // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
	0x03CA: "ι", // GREEK SMALL LETTER IOTA WITH DIALYTIKA
	0x03CB: "υ", // GREEK SMALL LETTER UPSILON WITH DIALYTIKA
	0x03CC: "ο", // GREEK SMALL LETTER OMICRON WITH TONOS
	0x03CD: "υ", // GREEK SMALL LETTER UPSILON WITH TONOS
	0x03CE: "ω", // GREEK SMALL LETTER OMEGA WITH TONOS
	0x03D3: "ϒ", // GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
	0x03D4: "ϒ", // GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL
	0x0400: "е", // CYRILLIC CAPITAL LETTER IE WITH GRAVE
	0x0401: "е", // CYRILLIC CAPITAL LETTER IO
	0x0403: "г", // CYRILLIC CAPITAL LETTER GJE
	0x0407: "і", // CYRILLIC CAPITAL LETTER YI
	0x040C: "к", // CYRILLIC CAPITAL LETTER KJE
	0x040D: "и", // CYRILLIC CAPITAL LETTER I WITH GRAVE
	0x040E: "у", // CYRILLIC CAPITAL LETTER SHORT U
	0x0419: "и", // CYRILLIC CAPITAL LETTER SHORT I
	0x0439: "и", // CYRILLIC SMALL LETTER SHORT I
	0x0450: "е", // CYRILLIC SMALL LETTER IE WITH GRAVE
	0x0451: "е", // CYRILLIC SMALL LETTER IO
	0x0453: "г", // CYRILLIC SMALL LETTER GJE
	0x0457: "і", // CYRILLIC SMALL LETTER YI
	0x045C: "к", // CYRILLIC SMALL LETTER KJE
	0x045D: "и", // CYRILLIC SMALL LETTER I WITH GRAVE
	0x045E: "у", // CYRILLIC SMALL LETTER SHORT U
	0x0476: "ѵ", // CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
	0x0477: "ѵ", // CYRILLIC SMALL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
	0x04C1: "ж", // CYRILLIC CAPITAL LETTER ZHE WITH BREVE
	0x04C2: "ж", // CYRILLIC SMALL LETTER ZHE WITH BREVE
	0x04D0: "а", // CYRILLIC CAPITAL LETTER A WITH BREVE
	0x04D1: "а", // CYRILLIC SMALL LETTER A WITH BREVE
	0x04D2: "а", // CYRILLIC CAPITAL LETTER A WITH DIAERESIS
	0x04D3: "а", // CYRILLIC SMALL LETTER A WITH DIAERESIS
	0x04D6: "е", // CYRILLIC CAPITAL LETTER IE WITH BREVE
	0x04D7: "е", // CYRILLIC SMALL LETTER IE WITH BREVE
	0x04DA: "ә", // CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS
	0x04DB: "ә", // CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS
	0x04DC: "ж", // CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS
	0x04DD: "ж", // CYRILLIC SMALL LETTER ZHE WITH DIAERESIS
	0x04DE: "з", // CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS
	0x04DF: "з", // CYRILLIC SMALL LETTER ZE WITH DIAERESIS
	0x04E2: "и", // CYRILLIC CAPITAL LETTER I WITH MACRON
	0x04E3: "и", // CYRILLIC SMALL LETTER I WITH MACRON
	0x04E4: "и", // CYRILLIC CAPITAL LETTER I WITH DIAERESIS
	0x04E5: "и", // CYRILLIC SMALL LETTER I WITH DIAERESIS
	0x04E6: "о", // CYRILLIC CAPITAL LETTER O WITH DIAERESIS
	0x04E7: "о", // CYRILLIC SMALL LETTER O WITH DIAERESIS
	0x04EA: "ө", // CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS
	0x04EB: "ө", // CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS
	0x04EC: "э", // CYRILLIC CAPITAL LETTER E WITH DIAERESIS
	0x04ED: "э", // CYRILLIC SMALL LETTER E WITH DIAERESIS
	0x04EE: "у", // CYRILLIC CAPITAL LETTER U WITH MACRON
	0x04EF: "у", // CYRILLIC SMALL LETTER U WITH MACRON
	0x04F0: "у", // CYRILLIC CAPITAL LETTER U WITH DIAERESIS
	0x04F1: "у", // CYRILLIC SMALL LETTER U WITH DIAERESIS
	0x04F2: "у", // CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE
	0x04F3: "у", // CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE
	0x04F4: "ч", // CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS
	0x04F5: "ч", // CYRILLIC SMALL LETTER CHE WITH DIAERESIS
	0x04F8: "ы", // CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS
	0x04F9: "ы", // CYRILLIC SMALL LETTER YERU WITH DIAERESIS
}
